CREATE DATABASE employee;
CREATE DATABASE "paidTimeOff";
CREATE DATABASE "payroll";
CREATE DATABASE "payslip";
CREATE DATABASE "benifit";
CREATE DATABASE "typeValidation";
CREATE DATABASE "user";
CREATE DATABASE chatbot ;