spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/