server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - AuthenticationFilter

        - id: chatbot-service
          uri: lb://chatbot-service
          predicates:
            - Path=/questions/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**
          filters:
            - AuthenticationFilter

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**
          filters:
            - AuthenticationFilter

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**
          filters:
            - AuthenticationFilter

        - id: payslip-service
          uri: lb://payslip-service
          predicates:
            - Path=/payslips/**

        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/payrolls/**

        - id: pto-service
          uri: lb://pto-service
          predicates:
            - Path=/paidTimesOff/**

        - id: benifit-service
          uri: lb://benifit-service
          predicates:
            - Path=/benifits/**

        - id: typeValidation-service
          uri: lb://typeValidation-service
          predicates:
            - Path=/typeValidations/**

  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"