server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**

  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"